### ISSUE TITLE
error in scheduling with setup matrix

### ISSUE THREAD

**Issue by ccandito** [frePPLe/frepple#145]
Dear All,
I've set up a setup matrix and the related changeover should last 20 minutes.
Unfortunately this is not taken into account in the concerned MO scheduling because the start and end dates haven't been changed (to MO 1017 from 1040 in the attached document).
Moreover the related resourse is loaded in a not proper way, that's there is an overload for productive time and the setup time is mixed up with the available time (please have a look at the concerned two pictures into the attached document).
Regards
claudio candito
[error in setup matrix.docx](https://github.com/frePPLe/frePPLe/files/721091/error.in.setup.matrix.docx)

**Comment by jdetaeye** [comment]
PLEASE read the first line of the documentation on setup matrices…
https://frepple.com/docs/4.0/user-guide/model-reference/setup-matrices.html

And this has also been brought up in earlier messages to this mailing list.





Johan De Taeye

Mob: +32 477.385.362

Skype: jdetaeye

Visit us at https://frepple.com



*From:* Claudio Candito [mailto:notifications@github.com]
*Sent:* Saturday, January 21, 2017 12:11 PM
*To:* frePPLe/frePPLe <frePPLe@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [frePPLe/frePPLe] error in scheduling with setup matrix (#145)



Dear All,
I've set up a setup matrix and the related changeover should last 20
minutes.
Unfortunately this is not taken into account in the concerned MO scheduling
because the start and end dates haven't been changed (to MO 1017 from 1040
in the attached document).
Moreover the related resourse is loaded in a not proper way, that's there
is an overload for productive time and the setup time is mixed up with the
available time (please have a look at the concerned two pictures into the
attached document).
Regards
claudio candito
error in setup matrix.docx
<https://github.com/frePPLe/frePPLe/files/721091/error.in.setup.matrix.docx>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/frePPLe/frePPLe/issues/145>, or mute the thread

**Comment by ccandito** [comment]
sorry for wasting your time
I've missed the statement: This feature is currently not ready for
production use yet.
regards
claudio

2017-01-21 12:15 GMT+01:00 Johan De Taeye <notifications@github.com>:
