### ISSUE TITLE
Full DB install Script

### ISSUE THREAD

**Issue by papyr** [frePPLe/frepple#341]
Hello, can you please include a full DB install script.

Also, I would like to help port and add Frepple compatibility to other free Databases.

thanks

**Comment by jdetaeye** [comment]
>>can you please include a full DB install script.

We already provide:
- windows installer includes an installation of postgres
- for linux distributions we have documtation on how to initialize the postgres package of the distribution eg https://frepple.org/docs/current/installation-guide/linux-binaries.php

>>Also, I would like to help port and add Frepple compatibility to other free Databases.

Early versions of frepple supported all databases that are supported by django: see https://docs.djangoproject.com/en/2.2/ref/databases/
We have completely given up on supporting databases, because:
- SQL is not standardised enough. Even basic functions as date&time functions, case sensistivity, ... are implemented differently.   IMHO SQL is a failed standard, really.
- postgresql rocks and we rely on the advanced features it provides
- we don't have the bandwidth to develop and test multiple databases

Sorry, I'm closing this ticket.

**Comment by papyr** [comment]
Hello, I hope you understand, I am ok if you dont want other flavors of SQL.

But, Im sorry having a simple DB install script is so important!
