### ISSUE TITLE
Two buffers on same item+location

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#377]
Hello,

in your documentation there is this information about Buffer "The combination item+location+batch is the unique primary key of this table." However, in your application creating two different buffers for one item on location is possible (batch is not populated).
I suppose there is a bug.

![obrazek](https://user-images.githubusercontent.com/86603226/126161108-e2a39c4c-f63a-46e3-ae1a-37c6562d4150.png)
![obrazek](https://user-images.githubusercontent.com/86603226/126161436-739b4ccd-c2e0-40ad-8cf5-9ab35a31b9eb.png)

**Comment by jdetaeye** [comment]
It was a bug indeed.

The fix is part of the upcoming release 6.16.0.
Until then the workaround is to populate the "batch" field with an empty string "".   Empty string "" is different from leaving the field null.  

For the techies:
- There behavior is caused by postgresql and not in the frepple code: https://www.postgresql.org/docs/12/indexes-unique.html   says "When an index is declared unique, multiple table rows with equal indexed values are not allowed. Null values are not considered equal. A multicolumn unique index will only reject cases where all indexed columns are equal in multiple rows."
- The above means that a unique-index with nullable fields isn't respected in postgresql.
- In our fix we made sure that the nullable fields always have a default different from null.

**Comment by petrakozielova** [comment]
Thank you for reply.

Ing. Petra Kozielová
Vývoj software

ELVAC SOLUTIONS s.r.o. | Hasičská 53 | 700 30 Ostrava – Hrabůvka | ČESKÁ REPUBLIKA
Email: ***@***.******@***.***>
www.elvacsolutions.eu<http://www.elvacsolutions.eu/>     www.infopanels.eu<http://www.infopanels.eu/>     www.techis.eu<http://www.techis.eu/>

***@***.***D6A886.5C5533A0]

ELVAC SOLUTIONS
