### ISSUE TITLE
Operation.SearchMode==MinCost, OperationMaterial.SearchMode==MinPenalty

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#400]
Hello,

I have two alternate operations with SearchMode==Cost and also Operation Resources with SearchMode==Minimum penalty.  I wonder why was two Manufacturing Orders created to the same resource. In log file I can see,that the resource has penalty 0 and the operation has penalty 1. Why is it that the resource has no penalty?

[AlternateResources_MinCost_vs_MinPenalty.xlsx](https://github.com/frePPLe/frepple/files/7121476/AlternateResources_MinCost_vs_MinPenalty.xlsx)

**Comment by jdetaeye** [comment]
Working as expected.

For both sales orders you find a similar section:
1) the operation 'verze 1' is choosen because it's the cheapest.
2) the resource "bruska 2" is choosen as both "bruska 1" and "bruska 2" are available on the requirement date -> 0 penalty on either one

![image](https://user-images.githubusercontent.com/5219207/132496794-0c3474f6-54a5-486c-916c-3aaef20a3c24.png)
