### ISSUE TITLE
Cant find the windows installer

### ISSUE THREAD

**Issue by julianbelina** [frePPLe/frepple#432]
I am unable to find the download location windows installer. There is an own article guiding the complete installation but no link to the download loaction :
https://frepple.org/docs/4.1/installation-guide/windows-installer.php

**Comment by jdetaeye** [comment]
The 4.1 release of this link is very old.   Don't even think of using that version :-)   We are at version 6.18 now.

We have dropped support for this windows installer since then.  (Why? Simply because for our paying enterprise customers we don't need it.  The open source community is the only one wishing a Windows installer, but that community as a whole doesn't contribute enough to make it a worthwhile effort for us to maintain it.)

The latest windows installer is found on the github release page https://github.com/frePPLe/frepple/releases
