### ISSUE TITLE
how to fix segmentation violation

### ISSUE THREAD

**Issue by onepiecewyz** [frePPLe/frepple#527]
i build the frepple application by docker, and already allocate memory enough. but this proble  comes up randomly and frequently, how to locate the root reasou or fix it? and can you briefly describe the memory allocation mechanism or task queue mechanism in freppple?

i have allocated 3G memory for frepple by command "docker update --memory 3072m --memory-swap 4096m frepple", and the compute process shows 250MB memory requirement as following picture.

![image](https://user-images.githubusercontent.com/21165646/168442328-fd7d38d9-13a2-4a11-806d-89f0ecb9329b.png)

**Comment by jdetaeye** [comment]
Until you catch the root cause and can confirm this is a product bug, please use a discussion https://github.com/frePPLe/frepple/discussions for this type of question

This crash is caused normally by bad/wrong data input that is bringing the engine in an unexpected state.   Set the parameter "plan.loglevel" to 9 to see better where the problem happens.    In many cases you can fix your data issue.
