### ISSUE TITLE
Some translations are not applied at all

### ISSUE THREAD

**Issue by OneManEquipe** [frePPLe/frepple#608]
## The problem

I'm trying to run an installation of the community edition, localized in my language of choice (Italian, but the problem applies also to others such as French). Currently I'm running it in the dev container, altered to use the `bullseye` image version instead of `focal` as I'm on ARM (Apple Silicon).

Some strings don't seem to be translated at all, for example `Capacity: respect capacity limits` in the `Admin -> Execute` page seems to stay in English no matter what.

This also happens on https://demo.frepple.com/execute/, regardless of the language the string doesn't seem to change (as I said I checked Italian and French).

Here is a screenshot of the panel from the demo website, as you can see there are several non-translated strings:
<img width="895" alt="image" src="https://github.com/frePPLe/frepple/assets/9056061/526f507e-bd76-4f7a-a640-284a691ecb22">

## Attempt at diagnosis

I'm not an expert on `.po` files, but my impression is that the problem is that the current files (e.g. `it.po`) show this:

```po
#: execute/management/commands/runplan.py:487
msgid "Capacity: respect capacity limits"
msgstr "Capacità: rispetto dei limiti di capacità"
```

The string in question, though, is not part of the `runplan.py` file, as it is instead in `freppledb/execute/templates/commands/runplan.html`.

## What I tried (no success)

I tried running the `./translations.sh extract` command, which.. kinda broke the file.

In particular, regarding the `Capacity: respect capacity limits` string, it leads to this in the `it.po` file:

```po
#: execute/templates/commands/runplan.html:44
#, fuzzy
msgid ""
"<span data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" data-bs-html="
"\"true\" data-bs-title=\"Respect the capacity limits of your resources."
"\">Capacity: respect capacity limits</span>"
msgstr ""
"<span data-bs-toggle=\"tooltip\" data-bs-placement=\"left\" data-bs-html="
"\"true\" data-bs-title=\"In push mode, any excess inventory will be "
"distributed downstream to child locations.\">Attiva la modalità push</span>"
```

and further down the file it shows this:

```po
#~ msgid "Capacity: respect capacity limits"
#~ msgstr "Capacità: rispetto dei limiti di capacità"
```

The former seems to be entirely wrong as the msgid and msgstr are not even related, while the second has no effect at all (and being commented I expect that it's not actually applied?). The upside is that it's now pointing to the correct file and line.

Regardless, the outcome is still the same after running a `./translations.sh compile` the application still shows the same string.

Am I doing something wrong?

**Comment by jdetaeye** [comment]
The correct string to translate is:   "<span data-bs-toggle=\"tooltip\" data-bs-placement=\"top\" data-bs-html="
"\"true\" data-bs-title=\"Respect the capacity limits of your resources."
"\">Capacity: respect capacity limits</span>"

Since this string was updated last it seems the "translations.sh extract" wasn't run. That's why https://demo.frepple.com/execute/ doesn't show these strings translated yet.    

The process to get this corrected:
- run "translations.sh extract"
- edit the master file "freppledb\locale\it\it.po" file with poedit or another translation editor
- run "translations.sh compile" to propagate the new translations to a number of files that are used by the application.

We'll include the refreshing of the language files in the next release 8.3

**Comment by jdetaeye** [comment]
https://github.com/frePPLe/frepple/commit/c478d2f37874132094cbcdb0fc791c6e8da9fe67   brings the translation files back in line with the latest source code.
